// components/RecipeForm.vue
<template>
  <div class="pb-24 bg-morandi-bg min-h-full">
    <!-- Image Upload Section -->
    <div 
      class="relative w-full h-64 bg-gray-200 flex items-center justify-center overflow-hidden cursor-pointer group"
      @click="!isCompressing && fileInputRef?.click()"
    >
      <div v-if="isCompressing" class="flex flex-col items-center text-morandi-primary">
        <Loader2 :size="48" class="mb-2 opacity-50 animate-spin" />
        <span class="text-sm font-medium opacity-70">{{ t('recipeForm.compressing') }}</span>
      </div>
      <img v-else-if="image" :src="image" alt="Preview" class="w-full h-full object-cover" />
      <div v-else class="flex flex-col items-center text-morandi-primary">
        <Camera :size="48" class="mb-2 opacity-50" />
        <span class="text-sm font-medium opacity-70">{{ t('recipeForm.addCoverPhoto') }}</span>
      </div>
      <div v-if="!isCompressing" class="absolute inset-0 bg-black/10 group-hover:bg-black/20 transition-colors" />
      <input 
        ref="fileInputRef"
        type="file" 
        accept="image/*" 
        class="hidden" 
        @change="handleImageUpload"
        :disabled="isCompressing"
      />
    </div>

    <div class="px-6 -mt-6 relative z-10">
      <div class="bg-morandi-surface rounded-t-3xl shadow-lg p-6 space-y-6">
        
        <!-- Basic Info -->
        <div class="space-y-4">
          <input
            type="text"
            :placeholder="t('recipeForm.recipeTitle')"
            v-model="title"
            class="w-full text-2xl font-serif font-bold text-morandi-text placeholder-gray-300 border-b border-transparent focus:border-morandi-primary focus:outline-none bg-transparent transition-all"
          />
          
          <div class="flex gap-4">
            <div class="flex-1">
              <label class="block text-xs font-bold text-morandi-subtext uppercase mb-1 tracking-wider">{{ t('recipeForm.category') }}</label>
              <select 
                v-model="category"
                class="w-full p-2 rounded-lg bg-morandi-bg text-morandi-text text-sm border-none focus:ring-1 focus:ring-morandi-primary outline-none"
              >
                <option v-for="c in categories" :key="c" :value="c">{{ getCategoryName(c) }}</option>
              </select>
            </div>
            <div class="flex-1">
              <label class="block text-xs font-bold text-morandi-subtext uppercase mb-1 tracking-wider">{{ t('recipeForm.time') }}</label>
              <div class="relative">
                <Clock :size="16" class="absolute left-2.5 top-2.5 text-morandi-accent" />
                <input 
                  type="text" 
                  v-model="prepTime"
                  :placeholder="t('recipeForm.timePlaceholder')"
                  class="w-full p-2 pl-9 rounded-lg bg-morandi-bg text-morandi-text text-sm border-none focus:ring-1 focus:ring-morandi-primary outline-none"
                />
              </div>
            </div>
          </div>

          <textarea
            :placeholder="t('recipeForm.descriptionPlaceholder')"
            v-model="description"
            @input="autoResizeTextarea($event.target as HTMLTextAreaElement)"
            rows="3"
            class="w-full p-3 rounded-lg bg-morandi-bg text-morandi-text text-sm resize-none focus:ring-1 focus:ring-morandi-primary outline-none resize-none overflow-hidden"
          />
        </div>

        <!-- Ingredients -->
        <div>
          <h3 class="text-lg font-semibold text-morandi-text mb-3">{{ t('recipeForm.ingredients') }}</h3>
          <div class="space-y-2">
            <div v-for="ing in ingredients" :key="ing.id" class="flex gap-2 items-center animate-fade-in">
              <div class="w-1.5 h-1.5 rounded-full bg-morandi-secondary flex-shrink-0" />
              <input
                type="text"
                :value="ing.text"
                @input="handleIngredientChange(ing.id, ($event.target as HTMLInputElement).value)"
                :placeholder="t('recipeForm.ingredientPlaceholder')"
                class="flex-grow p-2 bg-transparent border-b border-morandi-border focus:border-morandi-primary focus:outline-none text-sm text-morandi-text"
              />
              <button @click="removeIngredient(ing.id)" class="text-gray-300 hover:text-red-400">
                <X :size="18" />
              </button>
            </div>
          </div>
          <button 
            @click="handleAddIngredient"
            class="mt-3 text-sm font-medium text-morandi-primary hover:text-morandi-text flex items-center gap-1"
          >
            <Plus :size="16" /> {{ t('recipeForm.addIngredient') }}
          </button>
        </div>

        <!-- Steps -->
        <div>
          <h3 class="text-lg font-semibold text-morandi-text mb-3">{{ t('recipeForm.instructions') }}</h3>
          <div class="space-y-4">
            <div v-for="(step, index) in steps" :key="step.id" class="flex gap-3 animate-fade-in">
              <div class="flex-shrink-0 w-6 h-6 rounded-full bg-morandi-secondary/50 text-morandi-text text-xs font-bold flex items-center justify-center mt-1">
                {{ index + 1 }}
              </div>
              <textarea
                :value="step.text"
                @input="handleStepChange(step.id, $event.target as HTMLTextAreaElement)"
                :placeholder="t('recipeForm.stepPlaceholder')"
                rows="2"
                class="flex-grow p-2 bg-morandi-bg/50 rounded-lg text-sm text-morandi-text focus:bg-white focus:ring-1 focus:ring-morandi-primary outline-none transition-colors resize-none overflow-hidden"
              />
              <button @click="removeStep(step.id)" class="text-gray-300 hover:text-red-400 self-start mt-2">
                <Trash2 :size="16" />
              </button>
            </div>
          </div>
          <button 
            @click="handleAddStep"
            class="mt-3 text-sm font-medium text-morandi-primary hover:text-morandi-text flex items-center gap-1"
          >
            <Plus :size="16" /> {{ t('recipeForm.addStep') }}
          </button>
        </div>

        <!-- Action Buttons -->
        <div class="pt-4 flex gap-4">
          <button 
            @click="$emit('cancel')"
            class="flex-1 py-3 rounded-xl font-semibold text-morandi-text bg-morandi-bg hover:bg-gray-200 transition-colors"
          >
            {{ t('common.cancel') }}
          </button>
          <button 
            @click="handleSubmit"
            class="flex-1 py-3 rounded-xl font-semibold text-white bg-morandi-primary hover:opacity-90 transition-opacity shadow-md shadow-morandi-primary/30"
          >
            {{ t('recipeForm.saveRecipe') }}
          </button>
        </div>

      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, onMounted } from 'vue';
import { Camera, Plus, X, Clock, Trash2, Loader2 } from 'lucide-vue-next';
import { Recipe, Category, Ingredient, Step } from '../types';
import { compressImage, needsCompression, getImageSizeKB } from '../utils/imageCompress';
import { useLanguage } from '../composables/useLanguage';

interface Props {
  initialRecipe?: Recipe | null;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  save: [recipe: Omit<Recipe, 'id' | 'createdAt'> & { id?: string; createdAt?: number }];
  cancel: [];
}>();

const { t } = useLanguage();
const fileInputRef = ref<HTMLInputElement | null>(null);

const title = ref(props.initialRecipe?.title || '');
const description = ref(props.initialRecipe?.description || '');
const category = ref<Category>(props.initialRecipe?.category || Category.QUICK_BREAKFAST);
const image = ref(props.initialRecipe?.image || '');
const prepTime = ref(props.initialRecipe?.prepTime || '');
const isCompressing = ref(false);

const ingredients = ref<Ingredient[]>(
  props.initialRecipe?.ingredients || [{ id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`, text: '' }]
);

const steps = ref<Step[]>(
  props.initialRecipe?.steps || [{ id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`, text: '' }]
);

const categories = computed(() => Object.values(Category).filter(c => c !== 'All'));

const categoryMap: Record<string, string> = {
  [Category.QUICK_BREAKFAST]: 'categories.quickBreakfast',
  [Category.COLD_DISHES]: 'categories.coldDishes',
  [Category.MEAT_MAIN]: 'categories.meatMain',
  [Category.RICE_NOODLES]: 'categories.riceNoodles',
  [Category.SOUP]: 'categories.soup',
  [Category.VEGETABLE_STIR]: 'categories.vegetableStir',
  [Category.DESSERT]: 'categories.dessert',
  [Category.DRINKS]: 'categories.drinks',
};

const getCategoryName = (cat: Category) => {
  return t(categoryMap[cat] || cat);
};

const handleImageUpload = async (e: Event) => {
  const target = e.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;

  if (!file.type.startsWith('image/')) {
    alert(t('errors.imageCompressFailed'));
    return;
  }

  if (needsCompression(file, 800)) {
    isCompressing.value = true;
    try {
      const originalSizeKB = getImageSizeKB(file);
      console.log(`原始图片大小: ${originalSizeKB.toFixed(2)} KB，开始高质量压缩...`);
      
      const compressedImage = await compressImage(file, {
        maxWidth: 1920,
        maxHeight: 1920,
        quality: 0.95,
        maxSizeKB: 800,
        preserveFormat: true,
        lossless: false
      });
      
      const compressedSizeKB = (compressedImage.length * 3) / 4 / 1024;
      const compressionRatio = ((1 - compressedSizeKB / originalSizeKB) * 100).toFixed(1);
      console.log(`压缩后大小: ${compressedSizeKB.toFixed(2)} KB (压缩率: ${compressionRatio}%)`);
      
      image.value = compressedImage;
    } catch (error) {
      console.error('图片压缩失败:', error);
      alert(t('errors.imageCompressFailed'));
      const reader = new FileReader();
      reader.onloadend = () => {
        image.value = reader.result as string;
      };
      reader.readAsDataURL(file);
    } finally {
      isCompressing.value = false;
    }
  } else {
    const reader = new FileReader();
    reader.onloadend = () => {
      image.value = reader.result as string;
    };
    reader.readAsDataURL(file);
  }
};

const handleAddIngredient = () => {
  ingredients.value.push({ id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`, text: '' });
};

const handleIngredientChange = (id: string, text: string) => {
  const index = ingredients.value.findIndex(i => i.id === id);
  if (index !== -1) {
    ingredients.value[index].text = text;
  }
};

const removeIngredient = (id: string) => {
  if (ingredients.value.length > 1) {
    ingredients.value = ingredients.value.filter(i => i.id !== id);
  }
};

const handleAddStep = () => {
  steps.value.push({ id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`, text: '' });
};

const autoResizeTextarea = (textarea: HTMLTextAreaElement) => {
  textarea.style.height = 'auto';
  textarea.style.height = `${textarea.scrollHeight}px`;
};

const handleStepChange = (id: string, textarea: HTMLTextAreaElement) => {
  const index = steps.value.findIndex(s => s.id === id);
  if (index !== -1) {
    steps.value[index].text = textarea.value;
  }
  if (textarea) {
    autoResizeTextarea(textarea);
  }
};

const removeStep = (id: string) => {
  if (steps.value.length > 1) {
    steps.value = steps.value.filter(s => s.id !== id);
  }
};

const handleSubmit = (e: Event) => {
  e.preventDefault();
  
  if (!title.value.trim()) {
    const titleInput = document.querySelector(`input[placeholder="${t('recipeForm.recipeTitle')}"]`) as HTMLInputElement;
    if (titleInput) {
      titleInput.focus();
      titleInput.style.borderBottomColor = '#ef4444';
      setTimeout(() => {
        titleInput.style.borderBottomColor = '';
      }, 2000);
    }
    return;
  }
  
  const filteredIngredients = ingredients.value.filter(i => i.text.trim() !== '');
  const filteredSteps = steps.value.filter(s => s.text.trim() !== '');
  
  if (filteredIngredients.length === 0) {
    const firstIngredientInput = document.querySelector(`input[placeholder="${t('recipeForm.ingredientPlaceholder')}"]`) as HTMLInputElement;
    if (firstIngredientInput) {
      firstIngredientInput.focus();
    }
    return;
  }
  
  if (filteredSteps.length === 0) {
    const firstStepTextarea = document.querySelector(`textarea[placeholder="${t('recipeForm.stepPlaceholder')}"]`) as HTMLTextAreaElement;
    if (firstStepTextarea) {
      firstStepTextarea.focus();
    }
    return;
  }
  
  emit('save', {
    ...(props.initialRecipe ? { id: props.initialRecipe.id, createdAt: props.initialRecipe.createdAt } : {}),
    title: title.value,
    description: description.value,
    category: category.value,
    image: image.value || 'https://picsum.photos/800/600?random=99',
    prepTime: prepTime.value || '15 min',
    ingredients: filteredIngredients,
    steps: filteredSteps
  });
};

// 初始化所有有内容的textarea高度
onMounted(() => {
  const textareas = document.querySelectorAll('textarea');
  textareas.forEach(textarea => {
    if (textarea.value.trim() !== '') {
      autoResizeTextarea(textarea as HTMLTextAreaElement);
    }
  });
});
</script>

// components/RecipeForm.tsx
import React, { useState, useRef } from 'react';
import { Camera, Plus, X, Clock, Trash2, Loader2 } from 'lucide-react';
import { Recipe, Category, Ingredient, Step } from '../types';
import { compressImage, needsCompression, getImageSizeKB } from '../utils/imageCompress';
import { useLanguage } from '../contexts/LanguageContext';

interface RecipeFormProps {
  initialRecipe?: Recipe | null;
  onSave: (recipe: Omit<Recipe, 'id' | 'createdAt'> & { id?: string; createdAt?: number }) => void;
  onCancel: () => void;
}

export const RecipeForm: React.FC<RecipeFormProps> = ({ initialRecipe, onSave, onCancel }) => {
  const { t } = useLanguage();
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  const [title, setTitle] = useState(initialRecipe?.title || '');
  const [description, setDescription] = useState(initialRecipe?.description || '');
  const [category, setCategory] = useState<Category>(initialRecipe?.category || Category.QUICK_BREAKFAST);
  const [image, setImage] = useState<string>(initialRecipe?.image || '');
  const [prepTime, setPrepTime] = useState(initialRecipe?.prepTime || '');
  const [isCompressing, setIsCompressing] = useState(false);
  
  const [ingredients, setIngredients] = useState<Ingredient[]>(
    initialRecipe?.ingredients || [{ id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`, text: '' }]
  );
  
  const [steps, setSteps] = useState<Step[]>(
    initialRecipe?.steps || [{ id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`, text: '' }]
  );

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // 检查文件类型
    if (!file.type.startsWith('image/')) {
      alert(t('errors.imageCompressFailed'));
      return;
    }

    // 如果图片需要压缩（大于 800KB），进行高质量压缩
    if (needsCompression(file, 800)) {
      setIsCompressing(true);
      try {
        const originalSizeKB = getImageSizeKB(file);
        console.log(`原始图片大小: ${originalSizeKB.toFixed(2)} KB，开始高质量压缩...`);
        
        const compressedImage = await compressImage(file, {
          maxWidth: 1920,      // 提高分辨率限制
          maxHeight: 1920,
          quality: 0.95,       // 高质量（接近无损）
          maxSizeKB: 800,      // 提高大小限制
          preserveFormat: true, // 保持原始格式
          lossless: false      // 使用有损但高质量压缩
        });
        
        const compressedSizeKB = (compressedImage.length * 3) / 4 / 1024;
        const compressionRatio = ((1 - compressedSizeKB / originalSizeKB) * 100).toFixed(1);
        console.log(`压缩后大小: ${compressedSizeKB.toFixed(2)} KB (压缩率: ${compressionRatio}%)`);
        
        setImage(compressedImage);
      } catch (error) {
        console.error('图片压缩失败:', error);
        alert(t('errors.imageCompressFailed'));
        // 如果压缩失败，仍然尝试使用原图（但可能会超出存储限制）
        const reader = new FileReader();
        reader.onloadend = () => {
          setImage(reader.result as string);
        };
        reader.readAsDataURL(file);
      } finally {
        setIsCompressing(false);
      }
    } else {
      // 图片较小，直接使用（不压缩）
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleAddIngredient = () => {
    setIngredients([...ingredients, { id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`, text: '' }]);
  };

  const handleIngredientChange = (id: string, text: string) => {
    setIngredients(ingredients.map(i => i.id === id ? { ...i, text } : i));
  };

  const removeIngredient = (id: string) => {
    if (ingredients.length > 1) {
      setIngredients(ingredients.filter(i => i.id !== id));
    }
  };

  const handleAddStep = () => {
    setSteps([...steps, { id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`, text: '' }]);
  };

  const handleStepChange = (id: string, text: string) => {
    setSteps(steps.map(s => s.id === id ? { ...s, text } : s));
  };

  const removeStep = (id: string) => {
    if (steps.length > 1) {
      setSteps(steps.filter(s => s.id !== id));
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Validation
    if (!title.trim()) {
      // 使用更好的错误提示方式
      const titleInput = document.querySelector('input[placeholder="Recipe Title"]') as HTMLInputElement;
      if (titleInput) {
        titleInput.focus();
        titleInput.style.borderBottomColor = '#ef4444';
        setTimeout(() => {
          titleInput.style.borderBottomColor = '';
        }, 2000);
      }
      return;
    }
    
    const filteredIngredients = ingredients.filter(i => i.text.trim() !== '');
    const filteredSteps = steps.filter(s => s.text.trim() !== '');
    
    // 验证至少有一个ingredient和step
    if (filteredIngredients.length === 0) {
      const firstIngredientInput = document.querySelector('input[placeholder="Add ingredient"]') as HTMLInputElement;
      if (firstIngredientInput) {
        firstIngredientInput.focus();
      }
      return;
    }
    
    if (filteredSteps.length === 0) {
      const firstStepTextarea = document.querySelector('textarea[placeholder="Describe this step..."]') as HTMLTextAreaElement;
      if (firstStepTextarea) {
        firstStepTextarea.focus();
      }
      return;
    }
    
    onSave({
      ...(initialRecipe ? { id: initialRecipe.id, createdAt: initialRecipe.createdAt } : {}),
      title,
      description,
      category,
      image: image || 'https://picsum.photos/800/600?random=99',
      prepTime: prepTime || '15 min',
      ingredients: filteredIngredients,
      steps: filteredSteps
    });
  };

  return (
    <div className="pb-24 bg-morandi-bg h-full flex-1 overflow-y-auto">
      {/* Image Upload Section */}
      <div 
        className="relative w-full h-64 bg-gray-200 flex items-center justify-center overflow-hidden cursor-pointer group"
        onClick={() => !isCompressing && fileInputRef.current?.click()}
      >
        {isCompressing ? (
          <div className="flex flex-col items-center text-morandi-primary">
            <Loader2 size={48} className="mb-2 opacity-50 animate-spin" />
            <span className="text-sm font-medium opacity-70">{t('recipeForm.compressing')}</span>
          </div>
        ) : image ? (
          <img src={image} alt="Preview" className="w-full h-full object-cover" />
        ) : (
          <div className="flex flex-col items-center text-morandi-primary">
            <Camera size={48} className="mb-2 opacity-50" />
            <span className="text-sm font-medium opacity-70">{t('recipeForm.addCoverPhoto')}</span>
          </div>
        )}
        {!isCompressing && (
          <div className="absolute inset-0 bg-black/10 group-hover:bg-black/20 transition-colors" />
        )}
        <input 
          ref={fileInputRef}
          type="file" 
          accept="image/*" 
          className="hidden" 
          onChange={handleImageUpload}
          disabled={isCompressing}
        />
      </div>

      <div className="px-6 -mt-6 relative z-10">
        <div className="bg-morandi-surface rounded-t-3xl shadow-lg p-6 space-y-6">
          
          {/* Basic Info */}
          <div className="space-y-4">
            <input
              type="text"
              placeholder={t('recipeForm.recipeTitle')}
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full text-2xl font-serif font-bold text-morandi-text placeholder-gray-300 border-b border-transparent focus:border-morandi-primary focus:outline-none bg-transparent transition-all"
            />
            
            <div className="flex gap-4">
              <div className="flex-1">
                <label className="block text-xs font-bold text-morandi-subtext uppercase mb-1 tracking-wider">{t('recipeForm.category')}</label>
                <select 
                  value={category} 
                  onChange={(e) => setCategory(e.target.value as Category)}
                  className="w-full p-2 rounded-lg bg-morandi-bg text-morandi-text text-sm border-none focus:ring-1 focus:ring-morandi-primary outline-none"
                >
                  {Object.values(Category).filter(c => c !== 'All').map(c => (
                    <option key={c} value={c}>{c}</option>
                  ))}
                </select>
              </div>
              <div className="flex-1">
                <label className="block text-xs font-bold text-morandi-subtext uppercase mb-1 tracking-wider">{t('recipeForm.time')}</label>
                <div className="relative">
                  <Clock size={16} className="absolute left-2.5 top-2.5 text-morandi-accent" />
                  <input 
                    type="text" 
                    value={prepTime}
                    onChange={(e) => setPrepTime(e.target.value)}
                    placeholder={t('recipeForm.timePlaceholder')}
                    className="w-full p-2 pl-9 rounded-lg bg-morandi-bg text-morandi-text text-sm border-none focus:ring-1 focus:ring-morandi-primary outline-none"
                  />
                </div>
              </div>
            </div>

            <textarea
              placeholder={t('recipeForm.descriptionPlaceholder')}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={3}
              className="w-full p-3 rounded-lg bg-morandi-bg text-morandi-text text-sm resize-none focus:ring-1 focus:ring-morandi-primary outline-none"
            />
          </div>

          {/* Ingredients */}
          <div>
            <h3 className="text-lg font-semibold text-morandi-text mb-3">{t('recipeForm.ingredients')}</h3>
            <div className="space-y-2">
              {ingredients.map((ing) => (
                <div key={ing.id} className="flex gap-2 items-center animate-fade-in">
                  <div className="w-1.5 h-1.5 rounded-full bg-morandi-secondary flex-shrink-0" />
                  <input
                    type="text"
                    value={ing.text}
                    onChange={(e) => handleIngredientChange(ing.id, e.target.value)}
                    placeholder={t('recipeForm.ingredientPlaceholder')}
                    className="flex-grow p-2 bg-transparent border-b border-morandi-border focus:border-morandi-primary focus:outline-none text-sm text-morandi-text"
                  />
                  <button onClick={() => removeIngredient(ing.id)} className="text-gray-300 hover:text-red-400">
                    <X size={18} />
                  </button>
                </div>
              ))}
            </div>
            <button 
              onClick={handleAddIngredient}
              className="mt-3 text-sm font-medium text-morandi-primary hover:text-morandi-text flex items-center gap-1"
            >
              <Plus size={16} /> {t('recipeForm.addIngredient')}
            </button>
          </div>

          {/* Steps */}
          <div>
            <h3 className="text-lg font-semibold text-morandi-text mb-3">{t('recipeForm.instructions')}</h3>
            <div className="space-y-4">
              {steps.map((step, index) => (
                <div key={step.id} className="flex gap-3 animate-fade-in">
                  <div className="flex-shrink-0 w-6 h-6 rounded-full bg-morandi-secondary/50 text-morandi-text text-xs font-bold flex items-center justify-center mt-1">
                    {index + 1}
                  </div>
                  <textarea
                    value={step.text}
                    onChange={(e) => handleStepChange(step.id, e.target.value)}
                    placeholder={t('recipeForm.stepPlaceholder')}
                    rows={2}
                    className="flex-grow p-2 bg-morandi-bg/50 rounded-lg text-sm text-morandi-text focus:bg-white focus:ring-1 focus:ring-morandi-primary outline-none transition-colors"
                  />
                  <button onClick={() => removeStep(step.id)} className="text-gray-300 hover:text-red-400 self-start mt-2">
                    <Trash2 size={16} />
                  </button>
                </div>
              ))}
            </div>
            <button 
              onClick={handleAddStep}
              className="mt-3 text-sm font-medium text-morandi-primary hover:text-morandi-text flex items-center gap-1"
            >
              <Plus size={16} /> {t('recipeForm.addStep')}
            </button>
          </div>

          {/* Action Buttons */}
          <div className="pt-4 flex gap-4">
            <button 
              onClick={onCancel}
              className="flex-1 py-3 rounded-xl font-semibold text-morandi-text bg-morandi-bg hover:bg-gray-200 transition-colors"
            >
              {t('common.cancel')}
            </button>
            <button 
              onClick={handleSubmit}
              className="flex-1 py-3 rounded-xl font-semibold text-white bg-morandi-primary hover:opacity-90 transition-opacity shadow-md shadow-morandi-primary/30"
            >
              {t('recipeForm.saveRecipe')}
            </button>
          </div>

        </div>
      </div>
    </div>
  );
};
